








post0:
 date: "27 Novembro 2020"
 title: "Custo de Oportunidade: Conheça quais são as habilidades financeiras necessárias para garantir sucesso nas suas tomadas de decisões na hora de escolher sua residência."
 description: "Conheça quais são as habilidades financeiras necessárias para garantir sucesso nas suas tomadas de decisões na hora de escolher sua residência."
 link: "/custo-de-oportunidade.html"
 category: "Finanças"
 photo: "https://images.pexels.com/photos/4792376/pexels-photo-4792376.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video:
 text:
  "

<h4><strong>O custo de oportunidade &eacute; um conceito muito utilizado em economia para calcular o custo de uma tomada de decis&atilde;o versus o benef&iacute;cio da ren&uacute;ncia que foi obrigado a fazer diante dessa tomada de decis&atilde;o.</strong></h4>
<p><span style='font-weight: 400;'>Principalmente no mercado financeiro, &eacute; muito comum o investidor realizar o c&aacute;lculo de custo de oportunidade na hora de escolher onde aplicar seu dinheiro, mesmo de forma inconsciente.&nbsp;&nbsp;</span></p>
<p><span style='font-weight: 400;'>Entretanto, realizar o c&aacute;lculo do custo de oportunidade no mercado financeiro &eacute; mais f&aacute;cil do que fazer essa conta na tomada de decis&atilde;o profissional de um m&eacute;dico, por isso &eacute; muito importante entender quais premissas ser&atilde;o desenvolvidas para tomar uma decis&atilde;o mais assertiva, financeiramente falando.</span></p>
<p><span style='font-weight: 400;'>Dessa forma, s&atilde;o necess&aacute;rias a&ccedil;&otilde;es diversas para que a evolu&ccedil;&atilde;o da constru&ccedil;&atilde;o deste conceito seja realizada em etapas para potencializar suas tomadas de decis&otilde;es. Neste artigo, reunimos informa&ccedil;&otilde;es valiosas para ajudar voc&ecirc; a lidar com os desafios na hora de tomar decis&otilde;es profissionais que podem ter grandes impactos financeiros, passando pelos t&oacute;picos a seguir.</span></p>
<ul>
<li><strong>O que &eacute; um Custo de Oportunidade?</strong></li>
</ul>
<ul>
<li><strong>Como funciona o custo de oportunidade no mercado financeiro?</strong></li>
</ul>
<ul>
<li><strong>Quais os principais custos de oportunidades que aparecer&atilde;o na vida do m&eacute;dico?</strong></li>
</ul>
<ul>
<li><strong>Como um neurocirurgi&atilde;o economizou 1 milh&atilde;o de reais com uma tomada de decis&atilde;o?</strong></li>
</ul>
<p><span style='font-weight: 400;'>Continue a leitura para conferir!</span></p>
<p>&nbsp;</p>
<h4><strong>O que &eacute; um Custo de Oportunidade</strong></h4>
<p><span style='font-weight: 400;'>O custo de oportunidade &eacute; o valor de uma decis&atilde;o em rela&ccedil;&atilde;o a outra que voc&ecirc; deixou de tomar. Parece algo paradoxal, mas &eacute; bem simples de entender.</span></p>
<p><span style='font-weight: 400;'>Vamos come&ccedil;ar com um exemplo mais simples que n&atilde;o tem como mensurar o custo de oportunidade, mas que tem pesos diferentes para cada pessoa.</span></p>
<p><span style='font-weight: 400;'>Imagine uma pessoa obesa que deixa de malhar para comer uma sobremesa. O custo dessa escolha no m&eacute;dio e longo prazo na sa&uacute;de dessa pessoa ser&aacute; impactante, diferente de uma pessoa atl&eacute;tica que deixa de malhar um dia para comer uma sobremesa com a namorada.</span></p>
<p><span style='font-weight: 400;'>Com certeza o custo de oportunidade para cada um ser&aacute; diferente no m&eacute;dio e longo prazo.</span></p>
<p>&nbsp;</p>
<h3><strong>Como funciona o custo de oportunidade no mercado financeiro?</strong></h3>
<p><span style='font-weight: 400;'>O mesmo racional funciona no mercado financeiro, por&eacute;m de forma mais simples. Olhe que interessante, no passado um investimento conservador rendia em m&eacute;dia quase 1% ao m&ecirc;s, ent&atilde;o dificilmente um investidor se sentia atra&iacute;do para investir no mercado de a&ccedil;&otilde;es porque estaria assumindo um risco para buscar um retorno acima de 1% ao m&ecirc;s.</span></p>
<p><span style='font-weight: 400;'>Mas com a queda de juros, hoje um investimento conservador rende em m&eacute;dia 2% ao ano (se for na poupan&ccedil;a est&aacute; em torno de 1,4% ao ano). Assim, o investidor se sente mais atra&iacute;do para investir no mercado de a&ccedil;&otilde;es porque acredita que conseguir&aacute; um retorno maior.</span></p>
<p><span style='font-weight: 400;'>Ou seja, nessa situa&ccedil;&atilde;o &eacute; poss&iacute;vel visualizar o custo de oportunidade entre os cen&aacute;rios. Em momentos de juros altos no Brasil, o custo de oportunidade para investir na bolsa de valores &eacute; muito alto, ou seja, o investidor demanda um retorno muito maior em renda vari&aacute;vel para fazer sentido.</span></p>
<p><span style='font-weight: 400;'>J&aacute; em momentos de juros baixos, o custo de oportunidade para investir em renda vari&aacute;vel fica muito menor e, dessa forma, o investidor demanda um retorno menor para tomar essa decis&atilde;o, tudo baseado no custo de oportunidade.</span></p>
<p>&nbsp;</p>
<h3><strong>Quais os principais custos de oportunidades que aparecem na vida do m&eacute;dico?</strong></h3>
<p><span style='font-weight: 400;'>O mesmo princ&iacute;pio do mercado financeiro tamb&eacute;m &eacute; aplic&aacute;vel &agrave; &aacute;rea m&eacute;dica, de uma forma muito mais sutil.</span></p>
<p><span style='font-weight: 400;'>Come&ccedil;ado logo de cara quando o estudante de medicina se forma, para ele &eacute; mais interessante ingressar em uma resid&ecirc;ncia logo ap&oacute;s a formatura ou fazer um ano de plant&atilde;o para alavancar financeiramente?</span></p>
<p><span style='font-weight: 400;'>Para o m&eacute;dico, faz sentido atender pelo plano de sa&uacute;de ou somente particular? Qual o custo de oportunidade dessa decis&atilde;o?</span></p>
<p><span style='font-weight: 400;'>Ou ser&aacute; que vale a pena o m&eacute;dico investir em um equipamento m&eacute;dico ou alugar este equipamento por um per&iacute;odo?</span></p>
<p><span style='font-weight: 400;'>Enfim, em todas decis&otilde;es, o m&eacute;dico tem que comparar com outros cen&aacute;rios poss&iacute;veis para precificar e decidir pela melhor op&ccedil;&atilde;o a partir da cria&ccedil;&atilde;o de premissas de custos e receitas. Assim, &eacute; poss&iacute;vel comparar um cen&aacute;rio versou outro cen&aacute;rio.</span></p>
<p>&nbsp;</p>
<h3><strong>Como um neurocirurgi&atilde;o economizou 1 milh&atilde;o de reais com uma tomada de decis&atilde;o?</strong></h3>
<p><span style='font-weight: 400;'>H&aacute; um caso real de um residente em neurocirurgia que economizou 01milh&atilde;o de reais devido ao c&aacute;lculo do custo de oportunidade.</span></p>
<p><span style='font-weight: 400;'>Era um residente que estava no seu 3&ordm; ano e faltavam mais 2 anos para finalizar sua resid&ecirc;ncia, entretanto ele n&atilde;o estava satisfeito com o aprendizado que estava adquirindo no hospital.</span></p>
<p><span style='font-weight: 400;'>A ideia dele era desistir da resid&ecirc;ncia atual e ingressar novamente em outro hospital no qual acreditava que o aprendizado seria melhor.</span></p>
<p><span style='font-weight: 400;'>Mas antes que ele tomasse essa decis&atilde;o, foi feito o seguinte c&aacute;lculo para verificar o valor dessa decis&atilde;o (algo que normalmente a maioria dos profissionais n&atilde;o fazem).</span></p>
<p><span style='font-weight: 400;'>Para realizamos este c&aacute;lculo, tivemos que criar algumas premissas e cen&aacute;rios:</span></p>
<p>&nbsp;</p>
<h3><strong>Primeiro cen&aacute;rio: finalizar a resid&ecirc;ncia onde iniciou</strong></h3>
<p><span style='font-weight: 400;'>Tivemos que criar uma premissa de receita assim que ele finalizasse a resid&ecirc;ncia, e na m&eacute;dia, os profissionais que ele conhecia da &aacute;rea recebiam cerca de 30 mil reais por m&ecirc;s, ou seja, se ele iniciasse novamente a resid&ecirc;ncia, ficaria sem receber os 30 mil reais por 3 anos, o que equivale pr&oacute;ximo a </span><strong>um milh&atilde;o de reais (R$30.000,00 x 36 meses).</strong></p>
<p><span style='font-weight: 400;'>Perante este cen&aacute;rio, o residente de neurocirurgi&atilde;o deveria ponderar se o que ele deixasse de ganhar valeria a pena.</span></p>
<p><span style='font-weight: 400;'>Ent&atilde;o criamos um segundo cen&aacute;rio no qual ele realmente abre m&atilde;o de 3 anos de resid&ecirc;ncia e inicia do zero novamente, mas quando ele finalizar essa especializa&ccedil;&atilde;o (por considerar que estar&aacute; mais capacitado) a receita m&eacute;dia dele seria de 40 mil reais por m&ecirc;s, ou seja, 10 mil reais a mais em rela&ccedil;&atilde;o ao cen&aacute;rio anterior, mas essa diferen&ccedil;a para compensar o valor de um milh&atilde;o de reais que ele abriu m&atilde;o, demoraria aproximadamente 8 anos e 4 meses.</span></p>
<p><span style='font-weight: 400;'>Detalhe que em ambos os cen&aacute;rios nem utilizamos uma taxa de rentabilidade para sermos mais precisos nessa an&aacute;lise.</span></p>
<p><span style='font-weight: 400;'>De qualquer forma, criamos 2 cen&aacute;rios com valores para o residente em neurocirurgia decidir qual a melhor decis&atilde;o a tomar. Como voc&ecirc;s devem imaginar, ele finalizou sua resid&ecirc;ncia e est&aacute; ganhando acima do que t&iacute;nhamos previsto, mas este c&aacute;lculo foi fundamental na vida dele.</span></p>
<p><span style='font-weight: 400;'>A ferramenta custo de oportunidade ser&aacute; muito importante na vida dos seus clientes!</span></p>









  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post1:
 date: "7 Setembro 2020"
 title: "Liberdade Financeira"
 description: "Liberdade Financeira"
 link: "/liberdade-financeira.html"
 category: "Finanças"
 photo: "https://images.pexels.com/photos/2179602/pexels-photo-2179602.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video:
 text:
  "


<p>&nbsp;</p>
<h4><strong>Conte&uacute;do da semana: Foco em Liberdade Financeira</strong></h4>
<p><span style='font-weight: 400;'>07 de setembro &eacute; um marco importante para a hist&oacute;ria do Brasil, o dia em que o Brasil conquistou sua independ&ecirc;ncia de Portugal.&nbsp;</span></p>
<p><span style='font-weight: 400;'>Neste dia, o Brasil e sua popula&ccedil;&atilde;o obtiveram a t&atilde;o sonhada liberdade da col&ocirc;nia portuguesa.</span></p>
<p><span style='font-weight: 400;'>Anos depois, nesse mesmo dia, entendemos que os brasileiros devem refletir sobre como ir&atilde;o modelar a sua hist&oacute;ria.</span></p>
<p><span style='font-weight: 400;'>Entendemos que os brasileiros precisam, cada vez mais, pensar sobre como ir&atilde;o alcan&ccedil;ar a liberdade financeira, uma vez que grande parte da popula&ccedil;&atilde;o n&atilde;o economiza recursos financeiros.</span></p>
<p>&nbsp;</p>
<h4><strong>A provoca&ccedil;&atilde;o que fazemos &eacute;:</strong></h4>
<p><span style='font-weight: 400;'>Quando voc&ecirc; conquistar&aacute; sua independ&ecirc;ncia? Quando voc&ecirc; ir&aacute; atingir a sua liberdade financeira?</span></p>
<p><span style='font-weight: 400;'>Pode parecer clich&ecirc;, mas voc&ecirc; deve ficar preocupado com seu futuro financeiro, uma vez que tivemos uma reforma da previd&ecirc;ncia no ano passado e uma parcela grande da sociedade n&atilde;o sabe como essa reforma ir&aacute; impactar seu futuro.</span></p>
<p>&nbsp;</p>
<h4><strong>Vamos entender as regras da reforma da previd&ecirc;ncia:</strong></h4>
<p><span style='font-weight: 400;'>Para quem ingressou no mercado de trabalho em 2019...</span></p>
<p><span style='font-weight: 400;'>Benef&iacute;cio m&aacute;ximo previsto pela Previd&ecirc;ncia Social equivale a R$6.101,06*</span></p>
<p><span style='font-weight: 400;'>Para requerer a aposentadoria, o contribuinte precisar&aacute; ter:</span></p>
<p><span style='font-weight: 400;'>Mulher -&gt; idade m&iacute;nima de 62 anos e contribui&ccedil;&atilde;o m&iacute;nima de 15 anos</span></p>
<p><span style='font-weight: 400;'>Homem -&gt; idade m&iacute;nima de 65 anos e contribui&ccedil;&atilde;o m&iacute;nima de 20 anos&nbsp;</span></p>
<p><span style='font-weight: 400;'>O percentual do benef&iacute;cio ser&aacute; de 60% + 2% por ano de contribui&ccedil;&atilde;o que exceder a 15 anos (mulher) e 20 anos (homem).&nbsp;</span></p>
<p><span style='font-weight: 400;'>Esse percentual incidir&aacute; sobre a m&eacute;dia de 100% dos maiores sal&aacute;rios de contribui&ccedil;&atilde;o desde a compet&ecirc;ncia julho/1994 at&eacute; a data de entrada do requerimento.</span></p>
<p>&nbsp;</p>
<h4><strong>O percentual de benef&iacute;cio ser&aacute; de 100% para:</strong></h4>
<p><span style='font-weight: 400;'>Homens: com 40 anos de contribui&ccedil;&atilde;o</span></p>
<p><span style='font-weight: 400;'>Mulheres: com 35 anos de contribui&ccedil;&atilde;o</span></p>
<p><span style='font-weight: 400;'>O benef&iacute;cio nunca poder&aacute; ser inferior ao sal&aacute;rio m&iacute;nimo</span></p>
<p><span style='font-weight: 400;'>Em resumo, a atual aposentadoria est&aacute; mais desafiadora, por isso que devemos ter um plano B para complementar nossa aposentadoria.</span></p>
<p><span style='font-weight: 400;'>Se n&atilde;o vamos entrar para grande estat&iacute;stica, 98% dos brasileiros na 3&ordm; idade precisam continuar trabalham depois que aposentam ou da ajuda de um familiar ou amigo. Tenho certeza de que ningu&eacute;m quer isso.</span></p>
<p><span style='font-weight: 400;'>Por isso, o quanto antes iniciarmos a nossa estrat&eacute;gia para conquistar nossa independ&ecirc;ncia financeira, melhor ser&aacute; para voc&ecirc;!</span></p>
<p><span style='font-weight: 400;'>Se voc&ecirc; tiver um perfil conservador, considerando os juros atual de 2% ao ano, para juntarmos um milh&atilde;o de reais em:</span></p>
<p><span style='font-weight: 400;'>- 20 anos, vamos ter que juntar por ano, aproximadamente de R$41.156,72</span></p>
<p><span style='font-weight: 400;'>- 30 anos, vamos ter que juntar por ano, aproximadamente de R$24.649,92</span></p>
<p><span style='font-weight: 400;'>Enfim, quanto antes iniciarmos nossa estrat&eacute;gia para independ&ecirc;ncia financeira, mas fact&iacute;vel ela se torna!</span></p>





  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post2:
 date: "2 Dezembro 2020"
 title: "PORQUE SEU CLIENTE PRECISA DE UM PLANEJAMENTO FINANCEIRO PESSOAL"
 description: "Planejamento financeiro pessoal"
 link: "/planejamento-financeiro-pessoal.html"
 category: "Finanças"
 photo: "https://images.pexels.com/photos/3943716/pexels-photo-3943716.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video:
 text:
  "


<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Todo ser humano j&aacute; questionou sua exist&ecirc;ncia, sua origem e seu futuro. &Eacute; natural buscar a evolu&ccedil;&atilde;o constante para um futuro melhor.&nbsp;</span></p>
<p><span style='font-weight: 400;'>O mesmo questionamento se transporta para o cotidiano: metas profissionais, amorosas, pessoais, tudo para preencher o anseio de estar sempre um passo adiante do hoje e pr&oacute;ximo do amanh&atilde;. A palavra planejamento lembra previs&atilde;o, prepara&ccedil;&atilde;o e execu&ccedil;&atilde;o. Mas quem realmente j&aacute; se perguntou como ser&aacute; sua vida financeira, como realizar o seu prop&oacute;sito de vida?</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Estamos t&atilde;o modelados a seguir planos de outras pessoas, organiza&ccedil;&otilde;es e do pr&oacute;prio ambiente que vivemos que nos esquecemos dos nossos objetivos. Ser&aacute; que o estilo de vida dos sonhos est&aacute; de acordo com minhas a&ccedil;&otilde;es do presente? A transforma&ccedil;&atilde;o financeira ocorre a partir da transforma&ccedil;&atilde;o do modelo mental individual.</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>&nbsp;Alguns dos motivos que mais aprisionam os sonhos e projetos:</span></p>
<ol>
<li style='font-weight: 400;'><span style='font-weight: 400;'>Procrastina&ccedil;&atilde;o: A in&eacute;rcia das tarefas do cotidiano pode minar a mudan&ccedil;a necess&aacute;ria para a transforma&ccedil;&atilde;o da sua vida financeira. A n&atilde;o ser que o prazer da experi&ecirc;ncia positiva do futuro seja t&atilde;o &oacute;bvio que supere qualquer fardo do presente.</span></li>
<li style='font-weight: 400;'><span style='font-weight: 400;'>Execu&ccedil;&atilde;o: saber como agir em prol da mudan&ccedil;a &eacute; dif&iacute;cil, ainda&nbsp; mais quando n&atilde;o sabemos por onde come&ccedil;ar. Saiba que j&aacute; existem respostas para suas dores financeiras.</span></li>
<li style='font-weight: 400;'><span style='font-weight: 400;'>Tempo: tempo &eacute; dinheiro n&atilde;o &eacute; mesmo? Seu tempo deve ser investido em ganhar mais dinheiro naquilo que voc&ecirc; mais domina, para que tenha cada vez mais tempo livre para as coisas que te d&atilde;o prazer, sem se preocupar com o dinheiro.</span></li>
<li style='font-weight: 400;'><span style='font-weight: 400;'>Conhecimento: propriedade e dom&iacute;nio de causa financeira exigem anos de estrada e dedica&ccedil;&atilde;o. Planejar e fazer algo bem feito exige prepara&ccedil;&atilde;o minuciosa, isso pode te deixar confuso e sem direcionamento na hora de tomar uma decis&atilde;o.</span></li>
</ol>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>O planejamento financeiro pessoal &eacute; a solu&ccedil;&atilde;o ideal para quem ainda n&atilde;o venceu as barreiras entre o Hoje e o Amanh&atilde;.&nbsp;</span></p>
<p>&nbsp;</p>
<p><span style='font-weight: 400;'>Um servi&ccedil;o personalizado para transformar sonhos em realidade. Entender a realidade financeira, o momento de vida e os valores pessoais que guiam suas atitudes e acima de tudo compreendemos os projetos que fazem sentido para voc&ecirc;. Criar um planejamento financeiro pessoal para que o cliente consiga ter condi&ccedil;&otilde;es financeiras de conquistar esse estilo de vida e possa finalmente romper a barreira entre o Presente e o Futuro.</span></p>







  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------








