








post0:
 date: "27 Novembro 2020"
 title: "Custo de Oportunidade: Conheça quais são as habilidades financeiras necessárias para garantir sucesso nas suas tomadas de decisões na hora de escolher sua residência."
 description: "Conheça quais são as habilidades financeiras necessárias para garantir sucesso nas suas tomadas de decisões na hora de escolher sua residência."
 link: "/transformacoes-que-atraves-da-beleza-sao-entregues-em-produtos-de-varios-formatos.html"
 category: "Finanças"
 photo: "https://images.pexels.com/photos/4792376/pexels-photo-4792376.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video:
 text:
  "

<h4><strong>O custo de oportunidade &eacute; um conceito muito utilizado em economia para calcular o custo de uma tomada de decis&atilde;o versus o benef&iacute;cio da ren&uacute;ncia que foi obrigado a fazer diante dessa tomada de decis&atilde;o.</strong></h4>
<p><span style='font-weight: 400;'>Principalmente no mercado financeiro, &eacute; muito comum o investidor realizar o c&aacute;lculo de custo de oportunidade na hora de escolher onde aplicar seu dinheiro, mesmo de forma inconsciente.&nbsp;&nbsp;</span></p>
<p><span style='font-weight: 400;'>Entretanto, realizar o c&aacute;lculo do custo de oportunidade no mercado financeiro &eacute; mais f&aacute;cil do que fazer essa conta na tomada de decis&atilde;o profissional de um m&eacute;dico, por isso &eacute; muito importante entender quais premissas ser&atilde;o desenvolvidas para tomar uma decis&atilde;o mais assertiva, financeiramente falando.</span></p>
<p><span style='font-weight: 400;'>Dessa forma, s&atilde;o necess&aacute;rias a&ccedil;&otilde;es diversas para que a evolu&ccedil;&atilde;o da constru&ccedil;&atilde;o deste conceito seja realizada em etapas para potencializar suas tomadas de decis&otilde;es. Neste artigo, reunimos informa&ccedil;&otilde;es valiosas para ajudar voc&ecirc; a lidar com os desafios na hora de tomar decis&otilde;es profissionais que podem ter grandes impactos financeiros, passando pelos t&oacute;picos a seguir.</span></p>
<ul>
<li><strong>O que &eacute; um Custo de Oportunidade?</strong></li>
</ul>
<ul>
<li><strong>Como funciona o custo de oportunidade no mercado financeiro?</strong></li>
</ul>
<ul>
<li><strong>Quais os principais custos de oportunidades que aparecer&atilde;o na vida do m&eacute;dico?</strong></li>
</ul>
<ul>
<li><strong>Como um neurocirurgi&atilde;o economizou 1 milh&atilde;o de reais com uma tomada de decis&atilde;o?</strong></li>
</ul>
<p><span style='font-weight: 400;'>Continue a leitura para conferir!</span></p>
<p>&nbsp;</p>
<h4><strong>O que &eacute; um Custo de Oportunidade</strong></h4>
<p><span style='font-weight: 400;'>O custo de oportunidade &eacute; o valor de uma decis&atilde;o em rela&ccedil;&atilde;o a outra que voc&ecirc; deixou de tomar. Parece algo paradoxal, mas &eacute; bem simples de entender.</span></p>
<p><span style='font-weight: 400;'>Vamos come&ccedil;ar com um exemplo mais simples que n&atilde;o tem como mensurar o custo de oportunidade, mas que tem pesos diferentes para cada pessoa.</span></p>
<p><span style='font-weight: 400;'>Imagine uma pessoa obesa que deixa de malhar para comer uma sobremesa. O custo dessa escolha no m&eacute;dio e longo prazo na sa&uacute;de dessa pessoa ser&aacute; impactante, diferente de uma pessoa atl&eacute;tica que deixa de malhar um dia para comer uma sobremesa com a namorada.</span></p>
<p><span style='font-weight: 400;'>Com certeza o custo de oportunidade para cada um ser&aacute; diferente no m&eacute;dio e longo prazo.</span></p>
<p>&nbsp;</p>
<h3><strong>Como funciona o custo de oportunidade no mercado financeiro?</strong></h3>
<p><span style='font-weight: 400;'>O mesmo racional funciona no mercado financeiro, por&eacute;m de forma mais simples. Olhe que interessante, no passado um investimento conservador rendia em m&eacute;dia quase 1% ao m&ecirc;s, ent&atilde;o dificilmente um investidor se sentia atra&iacute;do para investir no mercado de a&ccedil;&otilde;es porque estaria assumindo um risco para buscar um retorno acima de 1% ao m&ecirc;s.</span></p>
<p><span style='font-weight: 400;'>Mas com a queda de juros, hoje um investimento conservador rende em m&eacute;dia 2% ao ano (se for na poupan&ccedil;a est&aacute; em torno de 1,4% ao ano). Assim, o investidor se sente mais atra&iacute;do para investir no mercado de a&ccedil;&otilde;es porque acredita que conseguir&aacute; um retorno maior.</span></p>
<p><span style='font-weight: 400;'>Ou seja, nessa situa&ccedil;&atilde;o &eacute; poss&iacute;vel visualizar o custo de oportunidade entre os cen&aacute;rios. Em momentos de juros altos no Brasil, o custo de oportunidade para investir na bolsa de valores &eacute; muito alto, ou seja, o investidor demanda um retorno muito maior em renda vari&aacute;vel para fazer sentido.</span></p>
<p><span style='font-weight: 400;'>J&aacute; em momentos de juros baixos, o custo de oportunidade para investir em renda vari&aacute;vel fica muito menor e, dessa forma, o investidor demanda um retorno menor para tomar essa decis&atilde;o, tudo baseado no custo de oportunidade.</span></p>
<p>&nbsp;</p>
<h3><strong>Quais os principais custos de oportunidades que aparecem na vida do m&eacute;dico?</strong></h3>
<p><span style='font-weight: 400;'>O mesmo princ&iacute;pio do mercado financeiro tamb&eacute;m &eacute; aplic&aacute;vel &agrave; &aacute;rea m&eacute;dica, de uma forma muito mais sutil.</span></p>
<p><span style='font-weight: 400;'>Come&ccedil;ado logo de cara quando o estudante de medicina se forma, para ele &eacute; mais interessante ingressar em uma resid&ecirc;ncia logo ap&oacute;s a formatura ou fazer um ano de plant&atilde;o para alavancar financeiramente?</span></p>
<p><span style='font-weight: 400;'>Para o m&eacute;dico, faz sentido atender pelo plano de sa&uacute;de ou somente particular? Qual o custo de oportunidade dessa decis&atilde;o?</span></p>
<p><span style='font-weight: 400;'>Ou ser&aacute; que vale a pena o m&eacute;dico investir em um equipamento m&eacute;dico ou alugar este equipamento por um per&iacute;odo?</span></p>
<p><span style='font-weight: 400;'>Enfim, em todas decis&otilde;es, o m&eacute;dico tem que comparar com outros cen&aacute;rios poss&iacute;veis para precificar e decidir pela melhor op&ccedil;&atilde;o a partir da cria&ccedil;&atilde;o de premissas de custos e receitas. Assim, &eacute; poss&iacute;vel comparar um cen&aacute;rio versou outro cen&aacute;rio.</span></p>
<p>&nbsp;</p>
<h3><strong>Como um neurocirurgi&atilde;o economizou 1 milh&atilde;o de reais com uma tomada de decis&atilde;o?</strong></h3>
<p><span style='font-weight: 400;'>H&aacute; um caso real de um residente em neurocirurgia que economizou 01milh&atilde;o de reais devido ao c&aacute;lculo do custo de oportunidade.</span></p>
<p><span style='font-weight: 400;'>Era um residente que estava no seu 3&ordm; ano e faltavam mais 2 anos para finalizar sua resid&ecirc;ncia, entretanto ele n&atilde;o estava satisfeito com o aprendizado que estava adquirindo no hospital.</span></p>
<p><span style='font-weight: 400;'>A ideia dele era desistir da resid&ecirc;ncia atual e ingressar novamente em outro hospital no qual acreditava que o aprendizado seria melhor.</span></p>
<p><span style='font-weight: 400;'>Mas antes que ele tomasse essa decis&atilde;o, foi feito o seguinte c&aacute;lculo para verificar o valor dessa decis&atilde;o (algo que normalmente a maioria dos profissionais n&atilde;o fazem).</span></p>
<p><span style='font-weight: 400;'>Para realizamos este c&aacute;lculo, tivemos que criar algumas premissas e cen&aacute;rios:</span></p>
<p>&nbsp;</p>
<h3><strong>Primeiro cen&aacute;rio: finalizar a resid&ecirc;ncia onde iniciou</strong></h3>
<p><span style='font-weight: 400;'>Tivemos que criar uma premissa de receita assim que ele finalizasse a resid&ecirc;ncia, e na m&eacute;dia, os profissionais que ele conhecia da &aacute;rea recebiam cerca de 30 mil reais por m&ecirc;s, ou seja, se ele iniciasse novamente a resid&ecirc;ncia, ficaria sem receber os 30 mil reais por 3 anos, o que equivale pr&oacute;ximo a </span><strong>um milh&atilde;o de reais (R$30.000,00 x 36 meses).</strong></p>
<p><span style='font-weight: 400;'>Perante este cen&aacute;rio, o residente de neurocirurgi&atilde;o deveria ponderar se o que ele deixasse de ganhar valeria a pena.</span></p>
<p><span style='font-weight: 400;'>Ent&atilde;o criamos um segundo cen&aacute;rio no qual ele realmente abre m&atilde;o de 3 anos de resid&ecirc;ncia e inicia do zero novamente, mas quando ele finalizar essa especializa&ccedil;&atilde;o (por considerar que estar&aacute; mais capacitado) a receita m&eacute;dia dele seria de 40 mil reais por m&ecirc;s, ou seja, 10 mil reais a mais em rela&ccedil;&atilde;o ao cen&aacute;rio anterior, mas essa diferen&ccedil;a para compensar o valor de um milh&atilde;o de reais que ele abriu m&atilde;o, demoraria aproximadamente 8 anos e 4 meses.</span></p>
<p><span style='font-weight: 400;'>Detalhe que em ambos os cen&aacute;rios nem utilizamos uma taxa de rentabilidade para sermos mais precisos nessa an&aacute;lise.</span></p>
<p><span style='font-weight: 400;'>De qualquer forma, criamos 2 cen&aacute;rios com valores para o residente em neurocirurgia decidir qual a melhor decis&atilde;o a tomar. Como voc&ecirc;s devem imaginar, ele finalizou sua resid&ecirc;ncia e est&aacute; ganhando acima do que t&iacute;nhamos previsto, mas este c&aacute;lculo foi fundamental na vida dele.</span></p>
<p><span style='font-weight: 400;'>A ferramenta custo de oportunidade ser&aacute; muito importante na vida dos seus clientes!</span></p>









  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------

post1:
 date: "17 Julho 2019"
 title: "O futuro do salão de beleza"
 description: "O futuro do seu salão está nessa lista?"
 link: "/o-futuro-do-salao-de-beleza.html"
 category: "Negócios"
 photo: "https://images.pexels.com/photos/356043/pexels-photo-356043.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
 video: " "
 text:
  "

<div><strong>O futuro do seu sal&atilde;o&nbsp;est&aacute; nessa lista?</strong></div>
<ol>
<li>Fechar as portas e mudar de &aacute;rea</li>
<li>Entregar o ponto e me adaptar ao digital</li>
<li>Manter firme porque vai passar</li>
<li>Vai funcionando com restri&ccedil;&otilde;es</li>
<li>Nem imagino como resolver essa situa&ccedil;&atilde;o</li>
</ol>
<p><br /><strong>1- Fechar as portas e mudar de &aacute;rea</strong><br /><br /><br /><em>Caramba</em>, essa &eacute; mesmo um alternativa a se considerar?<br /><br />Onde foi parar os estudos sobre o mercado de beleza e o quanto ele &eacute; promissor?<br /><br />Cad&ecirc; aquela&nbsp;<em>pessoa entusiasta</em>&nbsp;da autoestima que se tivesse outra fonte de renda, trabalharia at&eacute; de gra&ccedil;a s&oacute; pra ver os sorrisos no final?<br /><br />Que fim levou&nbsp;<em>aquele tempo dedicado a pesquisa</em>, que deu certeza de que beleza era o nicho que combinava com voc&ecirc;?<br /><br /><em>Quem vai te pagar o investimento</em>&nbsp;em tempo de estudo e de prepara&ccedil;&atilde;o pra empreender na beleza?<br /><br />Voc&ecirc; tem no&ccedil;&atilde;o que voc&ecirc; vai e o mercado fica, e n&atilde;o vai parar de crescer?<br /><br /><br /><br /><strong>2- &nbsp;Entregar o ponto e me adaptar ao digital</strong><br /><br />&Oacute;timo, mas voc&ecirc; j&aacute; sabe o que isso quer dizer?<br /><br />J&aacute; fez um plano de transi&ccedil;&atilde;o do f&iacute;sico pro digital?<br /><br />Pendurou na porta sua &nbsp;plaquinha &ldquo;mudamos para a Internet&rdquo;<br /><br />As chaves do seu novo endere&ccedil;o digital, ja est&aacute; na m&atilde;o?<br /><br />Devorou seu novo espa&ccedil;o digital?<br /><br />A comunica&ccedil;&atilde;o de como seu cliente chega no seu endere&ccedil;o, est&aacute; ok?<br /><br /><br /><br /><strong>3- Me manter firme porque vai passar</strong><br /><br /><br />Fico feliz em perceber que voc&ecirc; tem fundo de emerg&ecirc;ncia, mas at&eacute; quando?<br /><br />Os custos do aluguel e tudo mais, n&atilde;o est&atilde;o pesando?<br /><br />Existe algum contrato de fidelidade entre seu sal&atilde;o e seus clientes? Eles v&atilde;o te esperar?<br /><br />O que seus profissionais parceiros far&atilde;o durante essa pausa sem prazo?<br /><br /><br /><strong>4- Vai funcionando com restri&ccedil;&otilde;es</strong><br /><br />Voc&ecirc; j&aacute; conhece as restri&ccedil;&otilde;es necess&aacute;rias?<br /><br />Fez os c&aacute;lculos de quantos insumos a mais precisa investir?<br /><br />Fez os c&aacute;lculos de quantos atendimentos a menos precisa fazer?<br /><br />Seus profissionais parceiros v&atilde;o continuar com voc&ecirc;, mesmo com restri&ccedil;&otilde;es?<br /><br /><br /><strong>5- Nem imagino como resolver essa situa&ccedil;&atilde;o</strong><br /><br />Comece buscando solu&ccedil;&otilde;es:<br /><br />Fa&ccedil;a parte de comunidades de outros propriet&aacute;rios de sal&atilde;o de beleza. Estamos come&ccedil;ando uma no Telegram. Clique na figura pra ir direto.</p>



  "
#------------------------------------------------------- END POST -----------------------------------------------------------------------








